// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

interface IDeviceRegistry {
    enum DeviceType { Solar, Water, Biogas, Hydroponics, Bokashi_Home, Bokashi_Pro, Other }
    struct Device {
        string   deviceId;
        address  owner;
        uint256  registrationTime;
        bool     isActive;
        DeviceType deviceType;
        string   metadata;
        bytes    devicePublicKey;
        bytes    factorySignature;
        bytes32  attestationHash;
        uint256  lastAttestationTime;
    }
    function isDeviceValid(bytes32 deviceIdHash) external view returns (bool);
    function getDevice(bytes32 deviceIdHash) external view returns (Device memory);
}

interface IEmissionController {
    function recordBRU(address user, uint256 bruAmount) external;
}

interface IBokashiValidator {
    function getLatestCycleEndWeight(bytes32 deviceIdHash) external view returns (uint256);
}

/**
 * @title SoilTransferValidator
 * @notice Validates physical transfer of fermented Bokashi mass from Urban Users to Rural Farmers.
 *         Implements anti-cheat and awards BRU (Base Regenerative Units) scaled by GeoMultiplier.
 */
contract SoilTransferValidator is AccessControl {
    bytes32 public constant FARMER_REGISTRAR_ROLE = keccak256("FARMER_REGISTRAR_ROLE");

    IDeviceRegistry public deviceRegistry;
    IEmissionController public emissionController;
    IBokashiValidator public bokashiValidator;

    // Minimum kg required for transfer
    uint256 public constant MIN_TRANSFER_WEIGHT_G = 2000; // 2kg

    // BRU Math: 1.8 kg CO2-eq per kg of Bokashi diverted
    // In 18 decimals: 1 kg = 1.8 * 1e18 BRU
    // So 1 gram = 1.8 * 1e15 BRU
    uint256 public constant BRU_PER_GRAM = 18 * 1e14; 

    // Map used nonces to prevent QR replay attacks
    mapping(bytes32 => bool) public usedNonces;
    
    // Farmer Registry for MVP
    struct Farmer {
        address wallet;
        bool isActive;
        uint256 monthlyCapacityKg; 
    }
    mapping(bytes32 => Farmer) public registeredFarmers;

    event FarmerRegistered(bytes32 indexed farmerNodeId, address indexed wallet, uint256 capacityKg);
    event DropOffSettled(bytes32 indexed userDeviceId, bytes32 indexed farmerNodeId, uint256 receivedWeightG, uint256 totalBruAwarded, uint256 geoMultiplier);

    constructor(
        address _deviceRegistry, 
        address _emissionController, 
        address _bokashiValidator
    ) {
        require(_deviceRegistry != address(0), "Zero device registry");
        require(_emissionController != address(0), "Zero emission controller");
        require(_bokashiValidator != address(0), "Zero bokashi validator");

        deviceRegistry = IDeviceRegistry(_deviceRegistry);
        emissionController = IEmissionController(_emissionController);
        bokashiValidator = IBokashiValidator(_bokashiValidator);

        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(FARMER_REGISTRAR_ROLE, msg.sender);
    }

    function registerFarmer(bytes32 farmerNodeId, address wallet, uint256 capacityKg) external onlyRole(FARMER_REGISTRAR_ROLE) {
        require(wallet != address(0), "Invalid wallet");
        registeredFarmers[farmerNodeId] = Farmer({
            wallet: wallet,
            isActive: true,
            monthlyCapacityKg: capacityKg
        });
        emit FarmerRegistered(farmerNodeId, wallet, capacityKg);
    }

    /**
     * @notice User settles drop-off by providing a QR receipt generated by the farmer.
     * @param userDeviceId  The User's Bokashi device ID
     * @param farmerNodeId  The ID of the registered Farmer
     * @param receivedWeightG The weight of mass received by the Farmer (in grams)
     * @param distanceKm    Distance between user and farmer (provided by Oracle layer)
     * @param uniqueNonce   One-time random nonce generated by Farmer's App to prevent replay
     * @param farmerSignature ECDSA signature of (farmerNodeId, userDeviceId, receivedWeightG, distanceKm, uniqueNonce)
     */
    function settleDropOff(
        bytes32 userDeviceId,
        bytes32 farmerNodeId,
        uint256 receivedWeightG,
        uint256 distanceKm,
        bytes32 uniqueNonce,
        bytes memory farmerSignature
    ) external {
        // 1. Verify Nonce 
        require(!usedNonces[uniqueNonce], "Nonce already used");
        usedNonces[uniqueNonce] = true;

        // 2. Verify Farmer Signature (Anti-collusion / Authorization)
        {
            bytes32 messageHash = keccak256(abi.encodePacked(farmerNodeId, userDeviceId, receivedWeightG, distanceKm, uniqueNonce));
            address recoveredSigner = ECDSA.recover(MessageHashUtils.toEthSignedMessageHash(messageHash), farmerSignature);
            require(registeredFarmers[farmerNodeId].isActive, "Farmer node not active");
            require(recoveredSigner == registeredFarmers[farmerNodeId].wallet, "Invalid farmer signature");
        }

        // Setup output variables
        uint256 effectiveBru;
        uint256 geoMultiplier;

        // 3. Weight Correlation (Anti-cheat) & BRU Math
        {
            uint256 bucketWeight = bokashiValidator.getLatestCycleEndWeight(userDeviceId);
            require(bucketWeight >= MIN_TRANSFER_WEIGHT_G, "Did not meet 2kg threshold");
            require(receivedWeightG >= (bucketWeight * 90) / 100 && receivedWeightG <= (bucketWeight * 110) / 100, "Weight mismatch - possible fraud");

            // Max multiplier at 0km = 1.3x (13000 bps). Drops to 1.0x (10000 bps) at 20km.
            uint256 distancePenalty = distanceKm * 150;
            geoMultiplier = distancePenalty < 3000 ? 13000 - distancePenalty : 10000;

            // Final BRU applying GeoBonus
            effectiveBru = (((receivedWeightG * BRU_PER_GRAM) * geoMultiplier) / 10000);
        }

        // 4. Distribute
        {
            require(deviceRegistry.isDeviceValid(userDeviceId), "Invalid user device");
            // Fetch owner bypassing full struct mapping payload memory exhaustion
            address userOwner = deviceRegistry.getDevice(userDeviceId).owner;
            require(
                deviceRegistry.getDevice(userDeviceId).deviceType == IDeviceRegistry.DeviceType.Bokashi_Home ||
                deviceRegistry.getDevice(userDeviceId).deviceType == IDeviceRegistry.DeviceType.Bokashi_Pro,
                "Not a Bokashi device"
            );

            emissionController.recordBRU(userOwner, (effectiveBru * 70) / 100);
            emissionController.recordBRU(registeredFarmers[farmerNodeId].wallet, (effectiveBru * 30) / 100);
        }

        emit DropOffSettled(userDeviceId, farmerNodeId, receivedWeightG, effectiveBru, geoMultiplier);
    }
}
