const { ethers } = require("ethers");

/**
 * SCARAB Protocol - Hardware Node Validation Script
 * 
 * This script simulates the Web3 Backend / Oracle Network validation layer.
 * It reads the JSON payload generated by the ESPHome Custom C++ component
 * (scarab_crypto.h), hashes it, and verifies the cryptographic signature
 * to ensure data integrity before minting rewards.
 */

async function main() {
    console.log("=========================================");
    console.log("SCARAB Protocol - Node Authenticator Test");
    console.log("=========================================\n");

    // In a real environment, this payload is fetched via HTTP from the ESP32 IP
    // or received via MQTT/WebSocket.
    const mock_wattage = 1250.45;
    const simulatedPayloadFromESP32 = `{"device_id":"MOCK_ESP32_01","type":"SOLAR","power_w":${mock_wattage},"timestamp_ms":1771800000000}`;

    console.log("[1] Receiving Data from ESP32 Sensor...");
    console.log("    Data: ", simulatedPayloadFromESP32);

    // Instead of using real mbedtls in C++, we use a known test wallet here
    // to simulate what the ATECC608A chip does internally before sending data.
    const nodePrivateKey = "0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
    const nodeWallet = new ethers.Wallet(nodePrivateKey);
    console.log("\n[2] Simulated ATECC608A Internal Process...");
    console.log("    Node Public Address :", nodeWallet.address);

    // Hash the exact JSON string
    const messageHash = ethers.id(simulatedPayloadFromESP32);
    console.log("    Bytes32 Data Hash   :", messageHash);

    // The Hardware Chip signs the hash
    const signature = await nodeWallet.signMessage(ethers.getBytes(messageHash));
    console.log("    ECDSA Signature     :", signature);

    console.log("\n[3] Oracle Verification (Backend/Smart Contract)...");

    // The Oracle takes the plaintext payload and the signature provided by the node
    const verificationHash = ethers.id(simulatedPayloadFromESP32);
    const recoveredAddress = ethers.verifyMessage(ethers.getBytes(verificationHash), signature);

    console.log("    Recovered Signer    :", recoveredAddress);

    if (recoveredAddress === nodeWallet.address) {
        console.log("    Status              : ✅ VALID SIGNATURE");
        console.log(`    Action              : Authorize ${mock_wattage}W to EmissionController`);
    } else {
        console.log("    Status              : ❌ FAILED - TAMPERED DATA");
    }
}

main().catch(console.error);
